-- Upsert raw CSV fields for one Met object.
-- Image URL columns and bronze_* columns are deliberately NOT in the UPDATE
-- clause so that re-running `bootstrap` after enrichment does not clobber
-- prior enrichment results.

INSERT INTO met_artworks (
    object_id, object_number, is_highlight, is_public_domain, department,
    accession_year, object_name, title, culture, period, dynasty, reign,
    portfolio, artist_role, artist_display_name, artist_display_bio,
    artist_alpha_sort, artist_nationality, artist_begin_date, artist_end_date,
    artist_gender, artist_ulan_url, artist_wikidata_url,
    object_date, object_begin_date, object_end_date, medium, dimensions,
    credit_line, geography_type, city, state, county, country, region,
    subregion, locale, locus, excavation, river, classification,
    rights_and_reproduction, link_resource, object_wikidata_url, metadata_date,
    repository, tags, tags_aat_url, tags_wikidata_url, csv_loaded_at
) VALUES (
    :object_id, :object_number, :is_highlight, :is_public_domain, :department,
    :accession_year, :object_name, :title, :culture, :period, :dynasty, :reign,
    :portfolio, :artist_role, :artist_display_name, :artist_display_bio,
    :artist_alpha_sort, :artist_nationality, :artist_begin_date, :artist_end_date,
    :artist_gender, :artist_ulan_url, :artist_wikidata_url,
    :object_date, :object_begin_date, :object_end_date, :medium, :dimensions,
    :credit_line, :geography_type, :city, :state, :county, :country, :region,
    :subregion, :locale, :locus, :excavation, :river, :classification,
    :rights_and_reproduction, :link_resource, :object_wikidata_url, :metadata_date,
    :repository, :tags, :tags_aat_url, :tags_wikidata_url, :csv_loaded_at
)
ON CONFLICT(object_id) DO UPDATE SET
    object_number           = excluded.object_number,
    is_highlight            = excluded.is_highlight,
    is_public_domain        = excluded.is_public_domain,
    department              = excluded.department,
    accession_year          = excluded.accession_year,
    object_name             = excluded.object_name,
    title                   = excluded.title,
    culture                 = excluded.culture,
    period                  = excluded.period,
    dynasty                 = excluded.dynasty,
    reign                   = excluded.reign,
    portfolio               = excluded.portfolio,
    artist_role             = excluded.artist_role,
    artist_display_name     = excluded.artist_display_name,
    artist_display_bio      = excluded.artist_display_bio,
    artist_alpha_sort       = excluded.artist_alpha_sort,
    artist_nationality      = excluded.artist_nationality,
    artist_begin_date       = excluded.artist_begin_date,
    artist_end_date         = excluded.artist_end_date,
    artist_gender           = excluded.artist_gender,
    artist_ulan_url         = excluded.artist_ulan_url,
    artist_wikidata_url     = excluded.artist_wikidata_url,
    object_date             = excluded.object_date,
    object_begin_date       = excluded.object_begin_date,
    object_end_date         = excluded.object_end_date,
    medium                  = excluded.medium,
    dimensions              = excluded.dimensions,
    credit_line             = excluded.credit_line,
    geography_type          = excluded.geography_type,
    city                    = excluded.city,
    state                   = excluded.state,
    county                  = excluded.county,
    country                 = excluded.country,
    region                  = excluded.region,
    subregion               = excluded.subregion,
    locale                  = excluded.locale,
    locus                   = excluded.locus,
    excavation              = excluded.excavation,
    river                   = excluded.river,
    classification          = excluded.classification,
    rights_and_reproduction = excluded.rights_and_reproduction,
    link_resource           = excluded.link_resource,
    object_wikidata_url     = excluded.object_wikidata_url,
    metadata_date           = excluded.metadata_date,
    repository              = excluded.repository,
    tags                    = excluded.tags,
    tags_aat_url            = excluded.tags_aat_url,
    tags_wikidata_url       = excluded.tags_wikidata_url,
    csv_loaded_at           = excluded.csv_loaded_at;
