"""
The Dagster code location: assembles everything from the SourceSpec registry.

Entry point referenced by pyproject.toml ([tool.dagster] module_name). Assets, jobs,
checks and schedules are all GENERATED by looping ``sources.REGISTRY`` through the
factories -- so this file does not change when a source is added.

Two ways to obtain the code location:

* ``defs`` -- the module-level :class:`~dagster.Definitions` built from the default
  framework config + on-disk source registry. This is what ``dagster dev -m`` /
  ``dagster-webserver -m`` load. This module IS the manifest-backed entry point, so it
  imports the real dbt assets/resource.
* :func:`build_definitions` -- re-exported from :mod:`definition_factory`. Tests import
  that factory module directly and pass stub dbt assets/resources, assembling a code
  location WITHOUT importing the manifest-backed dbt asset module at collection time.
"""
from __future__ import annotations

from typing import List

from dagster import Definitions

from .assets_dbt import artwork_dbt_assets
from .config import FRAMEWORK
from .definition_factory import (
    assemble_definition_parts,
    build_definitions,
    derive_gold_marts,
)
from .resources import dbt_resource
from .sources import REGISTRY

# ---------------------------------------------------------------------------
# Module-level artifacts for the default code location.
#
# `defs` is what `dagster dev -m` / `dagster-webserver -m` load. The individual
# lists are also read by scripts/orchestration/doctor_orchestration.sh (asset/job/
# check counts), so they are kept as top-level names.
# ---------------------------------------------------------------------------
gold_marts: List[str] = derive_gold_marts(FRAMEWORK)
extraction_assets, asset_checks, jobs, schedules = assemble_definition_parts(
    FRAMEWORK,
    REGISTRY,
    artwork_dbt_assets,
    gold_marts=gold_marts,
)
jobs_by_name = {j.name: j for j in jobs}

defs = Definitions(
    assets=[*extraction_assets, artwork_dbt_assets],
    asset_checks=asset_checks,
    jobs=jobs,
    schedules=schedules,
    resources={"dbt": dbt_resource},
)
