"""The Dagster code location: assembles everything from the SourceSpec registry.

Entry point referenced by pyproject.toml ([tool.dagster] module_name). Assets,
jobs, checks and schedules are all GENERATED by looping ``sources.REGISTRY`` through
the factories -- so this file does not change when a museum is added.

Two ways to obtain the code location:

* ``defs`` -- the module-level :class:`~dagster.Definitions` built from the default
  framework config + on-disk source registry. This is what ``dagster dev -m`` /
  ``dagster-webserver -m`` load.
* :func:`build_definitions` -- a parameterized entry point that assembles a
  ``Definitions`` from an explicit framework config and/or ``sources`` directory, with
  injectable dbt assets/resource. Tests use this to assemble the code location against
  fixtures without relying on module globals.
"""
from __future__ import annotations

from typing import List, Optional

from dagster import Definitions

from .assets_dbt import artwork_dbt_assets
from .config import FRAMEWORK
from .dbt_manifest import gold_mart_names
from .factories.assets import build_source_assets
from .factories.checks import build_freshness_checks, build_source_checks
from .factories.jobs import build_jobs
from .factories.schedules import build_schedules
from .loader import load_source_specs
from .model import FrameworkConfig
from .resources import dbt_resource
from .sources import REGISTRY
from .spec import SourceRegistry


def _assemble(framework: FrameworkConfig, registry: SourceRegistry):
    """Build the extraction assets, checks, jobs and schedules from a registry.

    Pure: depends only on its arguments, so it is safe to call repeatedly (tooling,
    tests) and against fixture registries. Returns a 4-tuple.
    """
    # dbt Gold marts get a daily-cadence freshness check (not source-specific). The list
    # is DERIVED from the dbt manifest (models tagged 'marts') so it never needs
    # hand-editing; framework.yaml `gold_marts` is only a fallback before the manifest
    # is built.
    marts = gold_mart_names() or framework.freshness.gold_marts

    extraction_assets = [a for spec in registry for a in build_source_assets(spec)]
    asset_checks = [c for spec in registry for c in build_source_checks(spec)]
    asset_checks += build_freshness_checks(
        registry,
        gold_assets=marts,
        gold_lag_hours=framework.freshness.gold_lag_hours,
    )
    jobs = build_jobs(registry)
    schedules = build_schedules(registry, {j.name: j for j in jobs})
    return extraction_assets, asset_checks, jobs, schedules


def build_definitions(
    framework: Optional[FrameworkConfig] = None,
    sources_dir: Optional[str] = None,
    *,
    dbt_assets=None,
    dbt_resource_obj=None,
) -> Definitions:
    """Assemble a :class:`~dagster.Definitions` from explicit inputs.

    Args:
        framework: framework config to use; defaults to the loaded :data:`FRAMEWORK`.
        sources_dir: directory to scan for ``*.yaml`` source specs; defaults to the
            packaged ``sources/`` registry (:data:`REGISTRY`). Pass a temp dir to test
            that a new source needs zero framework ``.py`` edits.
        dbt_assets: dbt assets definition to include; defaults to the module-level
            ``artwork_dbt_assets``. Tests may pass a stub to avoid needing a manifest.
        dbt_resource_obj: the ``"dbt"`` resource; defaults to the module-level
            ``dbt_resource``. Tests may pass a stub.
    """
    fw = framework or FRAMEWORK
    registry: SourceRegistry = (
        SourceRegistry(load_source_specs(sources_dir)) if sources_dir is not None else REGISTRY
    )
    extraction_assets, asset_checks, jobs, schedules = _assemble(fw, registry)

    the_dbt_assets = dbt_assets if dbt_assets is not None else artwork_dbt_assets
    the_dbt_resource = dbt_resource_obj if dbt_resource_obj is not None else dbt_resource
    return Definitions(
        assets=[*extraction_assets, the_dbt_assets],
        asset_checks=asset_checks,
        jobs=jobs,
        schedules=schedules,
        resources={"dbt": the_dbt_resource},
    )


# ---------------------------------------------------------------------------
# Module-level artifacts for the default code location.
#
# `defs` is what `dagster dev -m` / `dagster-webserver -m` load. The individual
# lists are also read by scripts/orchestration/doctor_orchestration.sh (asset/job/
# check counts), so they are kept as top-level names.
# ---------------------------------------------------------------------------
gold_marts: List[str] = gold_mart_names() or FRAMEWORK.freshness.gold_marts
extraction_assets, asset_checks, jobs, schedules = _assemble(FRAMEWORK, REGISTRY)
jobs_by_name = {j.name: j for j in jobs}

defs = Definitions(
    assets=[*extraction_assets, artwork_dbt_assets],
    asset_checks=asset_checks,
    jobs=jobs,
    schedules=schedules,
    resources={"dbt": dbt_resource},
)
