"""The Dagster code location: assembles everything from the SourceSpec registry.

Entry point referenced by pyproject.toml ([tool.dagster] module_name). Assets,
jobs, checks and schedules are all GENERATED by looping ``sources.REGISTRY`` through
the factories -- so this file does not change when a museum is added.
"""
from __future__ import annotations

from dagster import Definitions

from .assets_dbt import artwork_dbt_assets
from .factories.assets import build_source_assets
from .factories.checks import build_freshness_checks, build_source_checks
from .factories.jobs import build_jobs
from .factories.schedules import build_schedules
from .resources import dbt_resource
from .sources import REGISTRY

# dbt Gold marts get a daily-cadence freshness check (not source-specific).
_GOLD_MARTS = ["dim_artists", "dim_artworks", "fct_artwork_images", "openaccess_catalog"]

extraction_assets = [a for spec in REGISTRY for a in build_source_assets(spec)]
asset_checks = [c for spec in REGISTRY for c in build_source_checks(spec)]
asset_checks += build_freshness_checks(REGISTRY, gold_assets=_GOLD_MARTS)

jobs = build_jobs(REGISTRY)
jobs_by_name = {j.name: j for j in jobs}
schedules = build_schedules(REGISTRY, jobs_by_name)

defs = Definitions(
    assets=[*extraction_assets, artwork_dbt_assets],
    asset_checks=asset_checks,
    jobs=jobs,
    schedules=schedules,
    resources={"dbt": dbt_resource},
)
