-- =============================================================================
-- create_grants.sql: Grant privileges to functional roles
-- (Renamed from grant_privileges.sql so teardown's create_->drop_ pairing rule
--  auto-maps it to drop_grants.sql; see scripts/manifest.txt + orchestrate.sh.)
-- Paired rollback: infrastructure/drop_grants.sql
-- =============================================================================

USE ROLE ARTWORK_ADMIN;

-- Warehouse usage for both roles
GRANT USAGE ON WAREHOUSE ARTWORK_WH TO ROLE ARTWORK_LOADER;
GRANT USAGE ON WAREHOUSE ARTWORK_WH TO ROLE ARTWORK_TRANSFORMER;

-- Database-level usage
GRANT USAGE ON DATABASE ARTWORK_DB TO ROLE ARTWORK_LOADER;
GRANT USAGE ON DATABASE ARTWORK_DB TO ROLE ARTWORK_TRANSFORMER;

-- ARTWORK_LOADER: full access to BRONZE only
GRANT USAGE ON SCHEMA ARTWORK_DB.BRONZE TO ROLE ARTWORK_LOADER;
GRANT CREATE TABLE ON SCHEMA ARTWORK_DB.BRONZE TO ROLE ARTWORK_LOADER;
GRANT CREATE STAGE ON SCHEMA ARTWORK_DB.BRONZE TO ROLE ARTWORK_LOADER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ARTWORK_DB.BRONZE TO ROLE ARTWORK_LOADER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA ARTWORK_DB.BRONZE TO ROLE ARTWORK_LOADER;
GRANT READ, WRITE ON ALL STAGES IN SCHEMA ARTWORK_DB.BRONZE TO ROLE ARTWORK_LOADER;
GRANT READ, WRITE ON FUTURE STAGES IN SCHEMA ARTWORK_DB.BRONZE TO ROLE ARTWORK_LOADER;
-- Loader must SELECT Bronze views (e.g. MET_WORKLIST) to drain the worklist for
-- its lease-claim MERGE. Tables/stages above do not cover the VIEW object class.
GRANT SELECT ON ALL VIEWS IN SCHEMA ARTWORK_DB.BRONZE TO ROLE ARTWORK_LOADER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ARTWORK_DB.BRONZE TO ROLE ARTWORK_LOADER;

-- ARTWORK_TRANSFORMER: read Bronze, full access to Silver and Gold
GRANT USAGE ON SCHEMA ARTWORK_DB.BRONZE TO ROLE ARTWORK_TRANSFORMER;
GRANT SELECT ON ALL TABLES IN SCHEMA ARTWORK_DB.BRONZE TO ROLE ARTWORK_TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ARTWORK_DB.BRONZE TO ROLE ARTWORK_TRANSFORMER;

GRANT USAGE ON SCHEMA ARTWORK_DB.SILVER TO ROLE ARTWORK_TRANSFORMER;
GRANT CREATE TABLE ON SCHEMA ARTWORK_DB.SILVER TO ROLE ARTWORK_TRANSFORMER;
GRANT CREATE VIEW ON SCHEMA ARTWORK_DB.SILVER TO ROLE ARTWORK_TRANSFORMER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ARTWORK_DB.SILVER TO ROLE ARTWORK_TRANSFORMER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA ARTWORK_DB.SILVER TO ROLE ARTWORK_TRANSFORMER;
GRANT SELECT ON ALL VIEWS IN SCHEMA ARTWORK_DB.SILVER TO ROLE ARTWORK_TRANSFORMER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ARTWORK_DB.SILVER TO ROLE ARTWORK_TRANSFORMER;

GRANT USAGE ON SCHEMA ARTWORK_DB.GOLD TO ROLE ARTWORK_TRANSFORMER;
GRANT CREATE TABLE ON SCHEMA ARTWORK_DB.GOLD TO ROLE ARTWORK_TRANSFORMER;
GRANT CREATE VIEW ON SCHEMA ARTWORK_DB.GOLD TO ROLE ARTWORK_TRANSFORMER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ARTWORK_DB.GOLD TO ROLE ARTWORK_TRANSFORMER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA ARTWORK_DB.GOLD TO ROLE ARTWORK_TRANSFORMER;
GRANT SELECT ON ALL VIEWS IN SCHEMA ARTWORK_DB.GOLD TO ROLE ARTWORK_TRANSFORMER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ARTWORK_DB.GOLD TO ROLE ARTWORK_TRANSFORMER;

-- ARTWORK_TRANSFORMER: dbt test audit schema (store_failures target)
GRANT USAGE ON SCHEMA ARTWORK_DB.DBT_TEST__AUDIT TO ROLE ARTWORK_TRANSFORMER;
GRANT CREATE TABLE ON SCHEMA ARTWORK_DB.DBT_TEST__AUDIT TO ROLE ARTWORK_TRANSFORMER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ARTWORK_DB.DBT_TEST__AUDIT TO ROLE ARTWORK_TRANSFORMER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA ARTWORK_DB.DBT_TEST__AUDIT TO ROLE ARTWORK_TRANSFORMER;
