-- =============================================================================
-- V006: Grant privileges to functional roles
-- ARTWORK_LOADER: write Bronze
-- ARTWORK_TRANSFORMER: read Bronze, write Silver and Gold
-- =============================================================================

USE ROLE ARTWORK_ADMIN;

-- Warehouse usage for both roles
GRANT USAGE ON WAREHOUSE ARTWORK_WH TO ROLE ARTWORK_LOADER;
GRANT USAGE ON WAREHOUSE ARTWORK_WH TO ROLE ARTWORK_TRANSFORMER;

-- Database-level usage
GRANT USAGE ON DATABASE ARTWORK_DB TO ROLE ARTWORK_LOADER;
GRANT USAGE ON DATABASE ARTWORK_DB TO ROLE ARTWORK_TRANSFORMER;

-- ARTWORK_LOADER: full access to BRONZE only
GRANT USAGE ON SCHEMA ARTWORK_DB.BRONZE TO ROLE ARTWORK_LOADER;
GRANT CREATE TABLE ON SCHEMA ARTWORK_DB.BRONZE TO ROLE ARTWORK_LOADER;
GRANT CREATE STAGE ON SCHEMA ARTWORK_DB.BRONZE TO ROLE ARTWORK_LOADER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ARTWORK_DB.BRONZE TO ROLE ARTWORK_LOADER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA ARTWORK_DB.BRONZE TO ROLE ARTWORK_LOADER;
GRANT READ, WRITE ON ALL STAGES IN SCHEMA ARTWORK_DB.BRONZE TO ROLE ARTWORK_LOADER;
GRANT READ, WRITE ON FUTURE STAGES IN SCHEMA ARTWORK_DB.BRONZE TO ROLE ARTWORK_LOADER;

-- ARTWORK_TRANSFORMER: read Bronze, full access to Silver and Gold
GRANT USAGE ON SCHEMA ARTWORK_DB.BRONZE TO ROLE ARTWORK_TRANSFORMER;
GRANT SELECT ON ALL TABLES IN SCHEMA ARTWORK_DB.BRONZE TO ROLE ARTWORK_TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ARTWORK_DB.BRONZE TO ROLE ARTWORK_TRANSFORMER;

GRANT USAGE ON SCHEMA ARTWORK_DB.SILVER TO ROLE ARTWORK_TRANSFORMER;
GRANT CREATE TABLE ON SCHEMA ARTWORK_DB.SILVER TO ROLE ARTWORK_TRANSFORMER;
GRANT CREATE VIEW ON SCHEMA ARTWORK_DB.SILVER TO ROLE ARTWORK_TRANSFORMER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ARTWORK_DB.SILVER TO ROLE ARTWORK_TRANSFORMER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA ARTWORK_DB.SILVER TO ROLE ARTWORK_TRANSFORMER;
GRANT SELECT ON ALL VIEWS IN SCHEMA ARTWORK_DB.SILVER TO ROLE ARTWORK_TRANSFORMER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ARTWORK_DB.SILVER TO ROLE ARTWORK_TRANSFORMER;

GRANT USAGE ON SCHEMA ARTWORK_DB.GOLD TO ROLE ARTWORK_TRANSFORMER;
GRANT CREATE TABLE ON SCHEMA ARTWORK_DB.GOLD TO ROLE ARTWORK_TRANSFORMER;
GRANT CREATE VIEW ON SCHEMA ARTWORK_DB.GOLD TO ROLE ARTWORK_TRANSFORMER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ARTWORK_DB.GOLD TO ROLE ARTWORK_TRANSFORMER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA ARTWORK_DB.GOLD TO ROLE ARTWORK_TRANSFORMER;
GRANT SELECT ON ALL VIEWS IN SCHEMA ARTWORK_DB.GOLD TO ROLE ARTWORK_TRANSFORMER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ARTWORK_DB.GOLD TO ROLE ARTWORK_TRANSFORMER;
