-- =============================================================================
-- V008 ROLLBACK: drop the ARTWORK_LOADER_SVC service user created by V008.
--
-- Paired forward: infrastructure/V008__create_service_user.sql.
-- Applied by:     scripts/rollback_sql.sh -> snow sql --filename
--                 --connection admin --enhanced-exit-codes.
--
-- Ordering:
--   `make down` runs V008 BEFORE V001 so the service user is removed before
--   its DEFAULT_ROLE (ARTWORK_LOADER) is dropped. With IF EXISTS on both
--   scripts the reverse order also succeeds; the ordering is purely a
--   convention for cleaner OBJECT_HISTORY trails.
--
-- Owned-object check:
--   DROP USER fails with:
--     090105 (22023): Cannot perform DROP USER. The current user is the
--                     owner of <n> objects.
--   if ARTWORK_LOADER_SVC owns any Snowflake object. By design, the service
--   user is least-privilege: V006 grants it INSERT / UPDATE / DELETE / SELECT
--   on BRONZE tables and READ / WRITE on stages, but does NOT grant
--   OWNERSHIP. Schemas and tables are owned by ARTWORK_ADMIN via V003 / V007.
--   If a future change grants OWNERSHIP to this user (for example, custom
--   tables created by the loader at runtime), transfer ownership back to
--   ARTWORK_ADMIN with:
--     GRANT OWNERSHIP ON <object> TO ROLE ARTWORK_ADMIN
--       REVOKE CURRENT GRANTS;
--   before invoking this rollback.
--
-- Credential cleanup:
--   The user's password and any registered RSA public key are removed
--   automatically with the user object. The matching `.env` file
--   (SNOWFLAKE_PASSWORD) and any operator-side key files are NOT touched by
--   this script and should be cleaned up manually if the account is being
--   decommissioned.
--
-- Idempotency:
--   DROP USER IF EXISTS is safe pre-create and safe to re-run.
-- =============================================================================

USE ROLE ACCOUNTADMIN;

DROP USER IF EXISTS ARTWORK_LOADER_SVC;
